/*!CK:3948134799!*//*1427086763,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["0GSt8"]); }

__d("InputAutoCapitalize",["CurrentLocale","Event","Input"],function(a,b,c,d,e,f,g,h,i){b.__markCompiled&&b.__markCompiled();var j={enable:function(k,l){var m=h.listen(k,'keyup',function(){if(!i.isEmpty(k)){var n=i.getValue(k);l=l||g.get();if(l=='tr_TR'&&n.substr(0,1)=='i'){i.setValue(k,"\u0130"+n.substr(1));}else i.setValue(k,n.substr(0,1).toLocaleUpperCase()+n.substr(1));m.remove();}});}};e.exports=j;},null);
__d("XUIOverlayButton.react",["AbstractButton.react","React","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){b.__markCompiled&&b.__markCompiled();var k=h.createClass({displayName:"XUIOverlayButton",render:function(){var l="_51tl selected";return (h.createElement(g,h.__spread({},this.props,{className:j(this.props.className,l)})));}});e.exports=k;},null);
__d("ComposerXHiddenInputClear",[],function(a,b,c,d,e,f){b.__markCompiled&&b.__markCompiled();function g(h){h.element.value='';}e.exports=g;},null);
__d("ComposerXSessionInputClear",[],function(a,b,c,d,e,f){b.__markCompiled&&b.__markCompiled();function g(h){h.element.value=(new Date()).valueOf().toString().substr(0,10);}e.exports=g;},null);
__d("CoverPromotionHandler",["AsyncDialog","AsyncRequest","BanzaiODS"],function(a,b,c,d,e,f,g,h,i){b.__markCompiled&&b.__markCompiled();var j={handleChooseClick:function(k,l){k.subscribe('itemclick',function(m,n){i.bumpEntityKey('cover_photo_upsell','choose');var o=new h(n.item.getValue()).setRelativeTo(l);g.send(o,function(p){});});}};e.exports=j;},null);
__d("FileFormDisableInFlight",["Form"],function(a,b,c,d,e,f,g){b.__markCompiled&&b.__markCompiled();function h(i){"use strict";this._form=i;}h.prototype.enable=function(){"use strict";this._subscription=this._form.subscribe(['submit','initial'],this._handle.bind(this));};h.prototype.disable=function(){"use strict";this._subscription.unsubscribe();this._subscription=null;};h.prototype._handle=function(i){"use strict";if(i==='submit'){setTimeout(g.setDisabled.bind(null,this._form.getRoot(),true),0);}else g.setDisabled(this._form.getRoot(),false);};e.exports=h;},null);
__d("QuestionsEigenpollForm",["DataStore","DOM","Form","Parent","isEmpty"],function(a,b,c,d,e,f,g,h,i,j,k){b.__markCompiled&&b.__markCompiled();var l={submit:function(m,n){if(k(i.serialize(m)))return;var o=function(r){return g.get(r,'optionid');},p=function(r){if(r!=m)i.setDisabled(r,true);};if(m.rendered_options)m.rendered_options.value=JSON.stringify(h.scry(j.byClass(m,'fbEigenpollRoot'),'.fbEigenpollRow').map(o));h.scry(j.byClass(m,'fbEigenpollRoot'),'.fbEigenpollRow .fbEigenpollForm').map(p);if(n){var q=h.find(m,'input[type="checkbox"]');q.checked=!q.checked;}return i.bootstrap(m);},insertNewOption:function(m,n,o){var p=function(t){return g.get(t,'optionid');},q=h.scry(m,'.fbEigenpollRow').map(p);for(var r=0;r<q.length;r++)if(q[r]==n)return;var s=h.scry(m,'.fbEigenpollAddOption');if(s.length==1){h.insertBefore(h.find(m,'.fbEigenpollAddOption'),o);}else h.insertAfter(h.scry(m,'.fbEigenpollRow').pop(),o);},replaceOption:function(m,n,o){h.scry(m,'.fbEigenpollRow').map(function(p){if(g.get(p,'optionid')==n)h.replace(p,o);});}};e.exports=l;},null);
__d("legacy:questions-eigenpoll-form",["QuestionsEigenpollForm"],function(a,b,c,d){b.__markCompiled&&b.__markCompiled();a.QuestionsEigenpollForm=b('QuestionsEigenpollForm');},3);
__d("QuestionsLimitedFacepile",["DOMQuery","copyProperties","Event"],function(a,b,c,d,e,f,g,h,i){b.__markCompiled&&b.__markCompiled();function j(k){this.init(k);}h(j.prototype,{init:function(k){var l=g.scry(k,'li.fbQuestionFacepileMoreItem')[0],m=l&&l.firstChild;if(m&&g.isNodeOfType(m,'span')){m.tabIndex=0;i.listen(m,'click',this._cancelEvent.bind(this));}},_cancelEvent:function(event){event.stop();}});e.exports=j;},null);
__d("QuestionsOpinionPollForm",["DOM"],function(a,b,c,d,e,f,g){b.__markCompiled&&b.__markCompiled();var h={replaceRow:function(i,j,k){var l='.pollRow_'+j;g.scry(i,l).map(function(m){g.replace(m,k);});}};e.exports=h;},null);
__d("legacy:QuestionsOpinionPollForm",["QuestionsOpinionPollForm"],function(a,b,c,d){b.__markCompiled&&b.__markCompiled();a.QuestionsOpinionPollForm=b('QuestionsOpinionPollForm');},3);
__d("QuestionsOptionTypeaheadView",["ContextualTypeaheadView"],function(a,b,c,d,e,f,g){b.__markCompiled&&b.__markCompiled();for(var h in g)if(g.hasOwnProperty(h))j[h]=g[h];var i=g===null?null:g.prototype;j.prototype=Object.create(i);j.prototype.constructor=j;j.__superConstructor__=g;function j(){"use strict";if(g!==null)g.apply(this,arguments);}j.prototype.render=function(k,l,m){"use strict";var n=l[0];if(k.trim()!==''&&n&&n.type!='calltoaction')l.unshift({text:k,type:'calltoaction'});return i.render.call(this,k,l,m);};e.exports=j;},null);